### ISSUE TITLE
Make Illegal States Unrepresentable

### ISSUE THREAD

**Issue by Masynchin** [mattrob33/grammateus#1]
Hello, @mattrob33!

I found your crate in the "New Crates" section in [crates.io](https://crates.io). I am interesting - what is your motivation to create this package? Are you a researcher in Greek history, or linguist, or something other?

I am also want to give you a tip how you can improve your code. As I can see a `GreekChar` is either have two or three bytes, but it isn't represented in its struct:

https://github.com/mattrob33/grammateus/blob/c325d16caf5e877785e99d1670c89dbbc123c5ce/src/greek_char.rs#L6-L10

Therefore, it requires to match its length if it is not 2 or 3, although we know it can not be:

https://github.com/mattrob33/grammateus/blob/c325d16caf5e877785e99d1670c89dbbc123c5ce/src/greek_char.rs#L322-L324

The approach to solve this problem is called "Make Illegal States Unrepresentable". In your case, we can make `GreekChar` not a byte array with its length, but enum with either two or three bytes, like this:

~~~rust
pub enum GreekChar {
    Two(u8, u8),
    Three(u8, u8, u8),
}
~~~

This will allow you to get rid of unreachable checks such as checking that length is not 2 or 3. For example, this is how `is_lowercase_greek` can be rewritten for new `GreekChar` enum (TODO is copied from source code):

~~~rust
pub fn is_lowercase_greek(char: &GreekChar) -> bool {
    match char {
        GreekChar::Two(0xCE, 0xB1..=0xBF) => true,
        GreekChar::Two(0xCF, 0x80..=0x89) => true,
        GreekChar::Two(_, _) => false,
        // TODO: implement is_lowercase for three-length char
        GreekChar::Three(_, _, _) => panic!("Not yet implented"),
    }
}
~~~

Now there is no need to check for length other than 2 or 3.

**Comment by mattrob33** [comment]
Thanks for taking time to make this suggestion! This seems like a great improvement I'll look into. I am new to Rust and still trying to pick up some best practices for Rust development, so I appreciate your help here.

**Comment by Masynchin** [comment]
> I am new to Rust and still trying to pick up some best practices for Rust development.

In this case I recommend you to take a look at [fmt](https://github.com/rust-lang/rustfmt) (code format) and [clippy](https://github.com/rust-lang/rust-clippy) (static analysis) plugins for cargo. These tools will help you to increase your code quality. Cheers!
